run_name: power_hybrid
seed: 42

data:
  train_csv: data/power/train.csv
  val_csv:   data/power/val.csv
  test_csv:  data/power/test.csv
  features:  ['MT_370', 'MT_196', 'MT_279', 'MT_364', 'MT_208', 'MT_339', 'MT_228']
  target:    MT_362
  seq_len: 96
  stride: 1

model:
  name: hybrid
  output_dim: 1
  d_model: 128
  lstm_hidden: 128
  lstm_layers: 1
  num_transformer_layers: 2
  nhead: 4
  dim_feedforward: 256
  dropout: 0.1
  pooling: last

train:
  batch_size: 128
  epochs: 40
  patience: 7
  lr: 1.0e-3
  weight_decay: 1.0e-4
