run_name: traffic_hybrid
seed: 42

data:
  train_csv: data/traffic/train.csv
  val_csv:   data/traffic/val.csv
  test_csv:  data/traffic/test.csv
  features:  ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10']
  target:    S0
  seq_len: 96
  stride: 1

model:
  name: hybrid
  output_dim: 1
  d_model: 128
  lstm_hidden: 128
  lstm_layers: 1
  num_transformer_layers: 2
  nhead: 4
  dim_feedforward: 256
  dropout: 0.1
  pooling: last

train:
  batch_size: 128
  epochs: 40
  patience: 7
  lr: 1.0e-3
  weight_decay: 1.0e-4
